import {
  STRIPE_PUBLISH_TEST,
  STRIPE_SECRET_TEST,
  STRIPE_PUBLISH_LIVE,
  STRIPE_SECRET_LIVE,
} from '@env';

export default {
  STRIPE_PUBLISH_TEST,
  STRIPE_SECRET_TEST,
  STRIPE_PUBLISH_LIVE,
  STRIPE_SECRET_LIVE,
};
